@url = http://localhost:3000

###


GET {{url}}/gatito

###
GET {{url}}/gatito/porId/1
# GET {{url}}/gatito/porId/67564c8d18e90708769a8708


###


POST {{url}}/gatito/agregar
Content-Type: application/json

# {
#     "nombre": "lorenzo",
#     "edad": 6,
#     "raza": "Egipcia",
#     "sexo": "Macho"
# }
{
    "id" : 3,
    "nombre": "lorenzo",
    "edad": 6,
    "raza": "Egipcia",
    "sexo": "Macho"
}


###

POST {{url}}/gatito/agregar
Content-Type: application/json

# {
#     "nombre": "lisst",
#     "edad": 2,
#     "raza": "Angora",
#     "sexo": "Macho"
# }
{
    "id" : 4,
    "nombre": "lisst",
    "edad": 2,
    "raza": "Angora",
    "sexo": "Macho"
}

###

POST {{url}}/gatito/agregar
Content-Type: application/json

# {
#     "nombre": "pedro",
#     "edad": 4,
#     "raza": "Naranja",
#     "sexo": "Macho"
# }
{
    "id": 5,
    "nombre": "Alberto",
    "edad": 4,
    "raza": "Naranja",
    "sexo": "Macho"
}

###


# PUT {{url}}/gatito/actualizar/67564c8d18e90708769a8708
PUT {{url}}/gatito/actualizar/1
Content-Type: application/json

{
    "id": 1,
    "nombre": "Pedrito",
    "edad": 4,
    "raza": "Siames",
    "sexo": "Macho"
}

###

DELETE {{url}}/gatito/delete/1